version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  producer:
    build: ./producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SEND_INTERVAL=5

  consumer:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
